name: kale
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - jupyterlab
  - numpy
  - vtk>=9.2.5
  - matplotlib
  - imageio>=2.5.0
  - imageio-ffmpeg
  - h5py
  - netcdf4
  - xarray
  - meshio
  - addict
  - colorcet
  - pyvista>=0.38.5
  - tqdm
  - trame>=2.2.6
  - trame-client>=2.4.2
  - trame-server>=2.8.0
  - trame-vtk>=2.4.4
  - pip
