name: kale
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - jupyterlab
  - numpy
  - vtk>=9.2.5
  - matplotlib
  - imageio>=2.5.0
  - h5py
  - netcdf4
  - xarray
  - ipyvtklink
  - colorcet
  - pyvista>=0.38.1
  - tqdm
  - pip
  - pip:
      - trame>=2.2.6
      - trame-client>=2.4.2
      - trame-server>=2.8.0
      - trame-vtk>=2.0.17
